### ISSUE TITLE
Slots Minigame

### ISSUE THREAD

**Issue by DobrovolskiyTV** [Bare7a/Streamlabs-Chatbot-Scripts#11]
HELLO! I want to ask a question. 
In the slot game what is the winning chance and how is it determined? Me in chat too often win, I don't like this :(

**Comment by mrhau93** [comment]
Hello,

from the settings you can specify a list of emotes that will be used for the slot (the defaults are "HSWP, TwitchRPG, MorphinTime, duDudu, HumbleLife, PJSalt"), plus a super emote (the default is "CurseLit"), this strings representations of the emotes are added to a python list

```
emotes = settings["emoteList"].replace(" ","").split(",")
emotes.append(settings["superEmote"].replace(" ",""))
```

3 random integers between 0 and the total number of emotes in the python list are generated simulating what a slot will do if you pull the lever, this 3 numbers are used to retrive the emotes that are at that specific position in the list

```
slot1 = emotes[Parent.GetRandom(0, len(emotes))]
slot2 = emotes[Parent.GetRandom(0, len(emotes))]
slot3 = emotes[Parent.GetRandom(0, len(emotes))]
```

at this point the script will check in order:

- If you have 3 equal emotes, in this case you can win the “super jackpot” or the “normal jackpot” depeing if your emote is the super emote or a normal emote.

```
if slots.count(slot1) == 3
# for the super jackpot:
multiplier = settings["rewardSuperJackpot"]
reward = costs * multiplier
# for the normal jackpot 
multiplier = settings["rewardJackpot"]
reward = costs * multiplier
```

- If you have two adjacent equal emotes: in this case you will win the “two same” reward.

```
elif (slot1 == slot2 or slot2 == slot3)
multiplier = settings["rewardTwoSame"]
reward = costs * multiplier
```

- If you have 2 non adjcent equal emotes: in this case you will win the “two seperated” reward.

```
elif (slot1 == slot3)
multiplier = settings["rewardTwoSeperated"]
reward = costs * multiplier
```

If all the above conditions are false you just lose your money.

**Comment by Bare7a** [comment]
@mrhau93 Explanation is 100% correct. If you want to lower the chance of winning on the slots minigame, just add more icons, that will significantly lower the rate.
