### ISSUE TITLE
No way to blacklist words

### ISSUE THREAD

**Issue by Brock09** [Bare7a/Streamlabs-Chatbot-Scripts#13]
People keep saying racist / sensitive things because there is no way to blacklist certain phrases / words.

**Comment by Bare7a** [comment]
I don't see a reason for me to create a script that blacklist words/phrases because Streamlabs Chatbot already has that functionality - https://www.youtube.com/watch?v=EOYDUBEsFAs you can use wildcards too https://en.wikipedia.org/wiki/Wildcard_character

**Comment by Brock09** [comment]
Although streamlabs chatbot can blacklist the words the SimpleTTS script will still read them out loud even though the bot deletes it as soon as its posted.

**Comment by Bare7a** [comment]
I've added BlackList for SimpleTTS, please test it, I don't have StreamlabsChatbot installed anymore. If you get an error please send the error log.
