### ISSUE TITLE
Permissions issue host winner

### ISSUE THREAD

**Issue by hostathon** [Bare7a/Streamlabs-Chatbot-Scripts#14]
AutoHosting/AutoHosting_StreamlabsSystem.py

For some reason when it comes time to host the winner, it states “you don’t have the permissions to post that”? I am not sure why that would be an issue since my Broadcaster is synced up to my streamlabs bot.

**Comment by Bare7a** [comment]
You must assign your bot as "Editor" - https://help.twitch.tv/s/article/Managing-Roles-for-your-Channel?language=en_US
