### ISSUE TITLE
Global name "message" is not defined error

### ISSUE THREAD

**Issue by Brock09** [Bare7a/Streamlabs-Chatbot-Scripts#16]
![Screenshot_1](https://user-images.githubusercontent.com/25409694/82539012-8b25bc00-9b01-11ea-942f-c1647b3a4b98.png)

Nothing happens when I click on the blacklist button and now the TTS doesn't work. Reverted to old version and it worked again.

**Comment by Ahnde** [comment]
Sadly I have no permission to push a branch and request a pull request, but here is how to fix the TTS module:

In the SimpleTTS_StreamlabsSystem.py file edit the first line in the 'Execute' function.
Replace `word in message.replace` `word in data.Message.replace`. Done

Furthermore, if u want to have the Open Blacklist button fixed, add this function to the same file:
`def OpenBlackList():
	location = os.path.join(os.path.dirname(__file__), "BlackList.txt")
	os.startfile(location)
	return`

**Comment by Bare7a** [comment]
> Sadly I have no permission to push a branch and request a pull request, but here is how to fix the TTS module:
> 
> In the SimpleTTS_StreamlabsSystem.py file edit the first line in the 'Execute' function.
> Replace `word in message.replace` with `word in data.Message.replace`. Done
> 
> Furthermore, if u want to have the Open Blacklist button fixed, add this function to the same file:
> 
> ```
> def OpenBlackList():
>         location = os.path.join(os.path.dirname(__file__), "BlackList.txt")
>         os.startfile(location)
>         return
> ```

I've applied your bugfix to the repo, thank you.
