### ISSUE TITLE
Bot cannot invoke !tts

### ISSUE THREAD

**Issue by merendi** [Bare7a/Streamlabs-Chatbot-Scripts#6]
My streamer account can use !tts but my bot cannot. Permissions are set to "Everyone". Any ideas why?

**Comment by Bare7a** [comment]
Streamlabs Chatbot by default doesn't let the bot account to use/write commands. Try a normal account instead.

**Comment by merendi** [comment]
Is it possible to use a command response like $tts("say this") then? I am trying to use TTS to say dynamic phrases when other commands in Streamlabs Chatbot are used.
