### ISSUE TITLE
Wont end

### ISSUE THREAD

**Issue by faerobelle** [Bare7a/Streamlabs-Chatbot-Scripts#7]
Trivia wont stop even when nobody is answering. Tried using a couple commands but nothing worked

**Comment by Bare7a** [comment]
What do you mean by "wont stop"? If no one answers the current question it is getting switched (it has an option to show the right answer if no one answered it correctly).

**Comment by faerobelle** [comment]
It doesn't stop running the script. I can't find anywhere to time out the
script after a certain amount of time after nobody answers the questions.

**Comment by Bare7a** [comment]
I haven't implemented that functionality
