### ISSUE TITLE
Sequence Contains No Elements

### ISSUE THREAD

**Issue by molokaidiver** [Bare7a/Streamlabs-Chatbot-Scripts#8]
Aloha,

I was trying to figure out why the Trivia minigame wouldn't send a message after giving the correct answer but I couldn't figure it out.

When I check the error log, it tells me "Sequence contains no elements" on Line 78 of the code.

If you need additional information, let me know.

**Comment by Bare7a** [comment]
To be honest I don't see why this error is thrown. BTW are you sure you are using Python v2.7.13?

**Comment by molokaidiver** [comment]
Sorry for the late reply. Yes, I'm using 2.7.13. However, I also had the latest version of Python installed. I just uninstalled the latest version and kept 2.7.13. I tested it again and it's showing me the same error. What I'll try and do is uninstall all Python related apps and reinstall 2.7.13 again and run the script again to see if it'll work. I'll keep you updated.
![chatbot](https://user-images.githubusercontent.com/27743039/51647187-d9cc4180-1f1f-11e9-9d2f-8cf57a1ea34c.jpg)

**Comment by molokaidiver** [comment]
So I uninstalled everything, ran CCleaner to make sure nothing was left in the temp folders and registry, reinstalled 2.7.13. Updated Streamlabs Chatbot to current version. Made sure the Lib folder was selected in the Scripts Settings (C:\Python27\Lib). Reloaded the scripts. Tried it again and it's still giving me the same error. The bot works except when I input the correct answer, I get the error seen in the screenshot. Not sure if OS matters but I'm running Windows 10 Pro x64. Lmk if you need anything else.

**Comment by Bare7a** [comment]
Can you send me your questions.txt file?
