### ISSUE TITLE
Default Trivia Questions won't stop

### ISSUE THREAD

**Issue by Croakk** [Bare7a/Streamlabs-Chatbot-Scripts#9]
So in the Trivia Questions it comes with two questions on the file as default "Whats between 1 & 3" and "What's the colour of Grass". Despite the answers being in the questions file, it would never give anyone in chat the right answer. So I decided to remove them from the Trivia Questions File, but the script still asks those questions all the time regardless if its in the Questions file or not.

**Comment by Bare7a** [comment]
Your questions.txt file is probably in some incorrect format, can you send it to me so I can check it?
